export interface AtlEquipmentItem {
  srNo: number;
  package: 'Package 1' | 'Package 2' | 'Package 3' | 'Package 4';
  name: string;
  spec: string;
  qty60: string; // Quantity for 60 students
  qty90: string; // Quantity for 90 students
  type: 'Consumable' | 'Equipment';
  application: string;
  category: string;
  refUrl: string;
}

export interface AtlOfficialLink {
  title: string;
  subtitle: string;
  url: string;
  isPdf?: boolean;
}

export interface AtlSubpageMeta {
  slug: string;
  title: string;
  shortTitle: string;
  eyebrow: string;
  badge: string;
  readTime: string;
  heroImage: string;
  heroImageAlt: string;
  tagline: string;
}

export const ATL_OFFICIAL_LINKS: AtlOfficialLink[] = [
  {
    title: 'NITI Aayog ATL Official Overview',
    subtitle: 'aim.gov.in/atl-overview.php — Atal Innovation Mission',
    url: 'https://aim.gov.in/atl-overview.php',
    isPdf: false
  },
  {
    title: 'Official ATL Equipment List (60 Students PDF)',
    subtitle: 'aim.gov.in Gazetted Specification for 60-Student Batches',
    url: 'https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf',
    isPdf: true
  },
  {
    title: 'Official ATL Equipment List (90 Students PDF)',
    subtitle: 'aim.gov.in Gazetted Specification for 90-Student Batches',
    url: 'https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_90_students.pdf',
    isPdf: true
  },
  {
    title: 'ATL Fund Utilization Guidelines (PDF)',
    subtitle: 'Official NITI Aayog Grant-in-Aid & PFMS Rulebook',
    url: 'https://aim.gov.in/pdf/ATL-Fund-Utilization-Guidelines.pdf',
    isPdf: true
  },
  {
    title: 'ATL Query & Compliance Resolution Portal',
    subtitle: 'atl.aim.gov.in — School Compliance & Tranche Dashboard',
    url: 'https://atl.aim.gov.in',
    isPdf: false
  },
  {
    title: 'PFMS Public Financial Management System',
    subtitle: 'pfms.nic.in — Central Treasury Scheme [0217]',
    url: 'https://pfms.nic.in',
    isPdf: false
  }
];

export const ATL_EQUIPMENT_DATA: AtlEquipmentItem[] = [
  {
    "srNo": 1,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Arduino Uno or equivalent",
    "spec": "ATmega328P - 8 bit AVR family microcontroller, equivalent or better. Operating Voltage: 5V Digital I/O Pins: 14 (of which 6 provide PWM output) PWM Digital I/O Pins : 6 Accessories : Case shell enclosure, compatible USB cable (length - 6 inch or more)",
    "qty60": "30 Units",
    "qty90": "45 Units",
    "type": "Consumable",
    "application": "Core embedded computing, sensor data acquisition, logic programming",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 2,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Arduino Nano or equivalent",
    "spec": "ATmega328P - 8 bit AVR family microcontroller, equivalent or better. Operating Voltage: 5V Digital I/O Pins : 14 (of which 6 provide PWM output) Analog Input Pins : 8 Accessories : Compatible USB cable ( length -6 inch or more) Quantity",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Core embedded computing, sensor data acquisition, logic programming",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 3,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Arduino Mega or equivalent",
    "spec": "ATmega 2560P - 8 bit AVR family microcontroller, equivalent or better. Operating Voltage: 5V Digital I/O Pins : 54 (of which 6 provide PWM output) Analog Input Pins: 16 Accessories: Case shell enclosure, Compatible USB cable ( length -6 inch or more)",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Core embedded computing, sensor data acquisition, logic programming",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 4,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Raspberry Pi 3 Model B+",
    "spec": "RASPBERRY PI 3 MODEL B+, equivalent or better Accessories - MicroSD card - 32 GB, USB 3.0 cable (1 meter), HDMI to VGA - 1 meter, HDMI to VGA adapter, Case shell enclosure",
    "qty60": "5 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Advanced edge computing, Python coding, Linux OS, camera AI computer vision",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 5,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Breadboards & Mini Breadboard",
    "spec": "Solderless 400 pin breadboard Solderless 800 pin breadboard 20 Self-Adhesive Proto Shield 20",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Solderless circuit prototyping, breakout testing, rapid electronic wiring",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 6,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "General Purpose solderable Board",
    "spec": "FR2 A Grade Material (140 x 90 mm)",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Solderless circuit prototyping, breakout testing, rapid electronic wiring",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 7,
    "package": "Package 1",
    "category": "General",
    "name": "FR2 A Grade Material (80 x 55 mm)",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 8,
    "package": "Package 1",
    "category": "Berg Strips",
    "name": "Female Berg Strip, 2.54mm pitch, 40 pin single row, breakable pin",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Solderless circuit prototyping, breakout testing, rapid electronic wiring",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 9,
    "package": "Package 1",
    "category": "General",
    "name": "Male Berg Strip, 2.54mm pitch, 40 pin single row, breakable pin",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Solderless circuit prototyping, breakout testing, rapid electronic wiring",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 10,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "16x2 LCD display",
    "spec": "Dot matrix LCD display. 16 characters X 2 lines. I2C",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Visual alphanumeric and graphic data output, student telemetry displays",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 11,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "USB Cables",
    "spec": "USB Cable Set (A to B, 12 inch or more)",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 12,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "USB Cables",
    "spec": "USB Cable Set (Mini, 12 inches or more)",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 13,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Battery",
    "spec": "9-12V 2000 to 2500 mAh rechargeable battery with 2 chargers. Equivalent or better Quantity",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 14,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Resistor Kit",
    "spec": "One kit contains - 30 carbon film resistors of 20 different resistance values each assorted, packaged together and labelled. Wattage: 0.125W to 1W Values: 0Ω, 1.5Ω, 4.7Ω, 10Ω, 47Ω, 100Ω, 220Ω, 330Ω, 470Ω, 680Ω, 1kΩ, 2.2kΩ, 3.3kΩ, 4.7kΩ, 10kΩ, 22kΩ, 47kΩ, 100kΩ, 330kΩ, 1MΩ",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Fundamental passive electronics, current limiting, filtering, switching circuits",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 15,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Capacitor Kit",
    "spec": "One kit contains - 20 electrolytic capacitors of 10 different capacitance values each. Assorted kit packaged together and labelled. Values: 10pF, 22pF, 100pF, 1nF, 10nF, 100nF, 1µF, 10µF, 100µF, 1000µF",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Fundamental passive electronics, current limiting, filtering, switching circuits",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 16,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Linear Voltage Regulator",
    "spec": "7805, 7812,7809",
    "qty60": "30 Units",
    "qty90": "45 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 17,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Water Pump module",
    "spec": "DC12V 3W Submersible Water Pump",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 18,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Piezoelectric Plate",
    "spec": "Normal Copper based 4 cm Diameter approx.",
    "qty60": "30 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 19,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "8*8 LED Matrix Module",
    "spec": "Max7219 Dot LED Matrix Module. MCU Control LED Display Module",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Visual alphanumeric and graphic data output, student telemetry displays",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 20,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Bluetooth module",
    "spec": "HC 05 Bluetooth module Voltage Rating: 5 V",
    "qty60": "15 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 21,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "7 Segment Led Display",
    "spec": "LED 4-Digit Display Module Voltage Rating: 2.4V to 5.5V 4-Pin interface: Vcc, Gnd, Data, Clock",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Visual alphanumeric and graphic data output, student telemetry displays",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 22,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "GSM",
    "spec": "Sim900 GPRS Transfer Board Micro Sim Gsm Core TTL Port Module for Arduino",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 23,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "GPS",
    "spec": "GY-NEO6MV2 new GPS module",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 24,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Laser Diode Emitter",
    "spec": "650 nm 5mW Mini Laser Dot Diode Module Quantity",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Fundamental passive electronics, current limiting, filtering, switching circuits",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 25,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LDR Module",
    "spec": "5mm/12mm, Photosensitive LDR Light Sensor Module",
    "qty60": "30 Units",
    "qty90": "45 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 26,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Keypad",
    "spec": "Universal 16 Key Switch Keypad",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 27,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "JoyStick",
    "spec": "2-axis joystick with push button function",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 28,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Active Buzzer",
    "spec": "Small 5 volt",
    "qty60": "40 Units",
    "qty90": "60 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 29,
    "package": "Package 1",
    "category": "General",
    "name": "Big 5 volt",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "40 Units",
    "qty90": "60 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 30,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Motor driver Module",
    "spec": "L293D",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 31,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Sound Playback Module",
    "spec": "ISD1820 voice recording module or equivalent",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 32,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "DC Plastic Gear motor with wheel",
    "spec": "12V, 150RPM, Side Shaft BO (Battery operation) Motor",
    "qty60": "40 Units",
    "qty90": "60 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 33,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Node MCU",
    "spec": "ESP 8266 I2C, 1 wire, plug and play",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 34,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "WeMos D1 R2",
    "spec": "WeMos D1 R2 with WiFi ESP 8266 Operating Voltage: 5V",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 35,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Vibrating Motor",
    "spec": "Weight: 10 Grams Operating Voltage: 1.5 to 3V",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 36,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Alligator Connectors",
    "spec": "Multi-Colour Alligator Connectors - 12 inch",
    "qty60": "200 Units",
    "qty90": "300 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 37,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Battery clips with DC Jack",
    "spec": "9-volt battery clips with DC Jack",
    "qty60": "40 Units",
    "qty90": "40 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 38,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Hook-up Wires",
    "spec": "Red & Black set 100 Meters each",
    "qty60": "4 Units",
    "qty90": "4 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 39,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Jumper Cable",
    "spec": "Male-Male Male-Female 600 Female-Female 400",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 40,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "RGB LEDs",
    "spec": "Regular 5mm 3-5 volt Range",
    "qty60": "400 Units",
    "qty90": "600 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 41,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LEDs (Red)",
    "spec": "Regular 5mm 3-5 volt Range",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 42,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LEDs (Green)",
    "spec": "Regular 5mm 3-5 volt Range",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 43,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LEDs (Blue)",
    "spec": "Regular 5mm 3-5 volt Range",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 44,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LEDs (Yellow)",
    "spec": "Regular 5mm 3-5 volt Range",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 45,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "LEDs (White)",
    "spec": "Regular 5mm 3-5 volt Range Quantity",
    "qty60": "1000 Units",
    "qty90": "1500 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 46,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Timer IC - LM 555",
    "spec": "LM 555 Timer IC. Voltage range - 4.5V to 16V",
    "qty60": "30 Units",
    "qty90": "45 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 47,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Atmega16u2",
    "spec": "8 bit microcontroller Individual IC (DIP). Voltage range: 2.7V to 5.5V. Operational Range: -40°C to +80°C",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Core embedded computing, sensor data acquisition, logic programming",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 48,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Diodes and Transistors Kit",
    "spec": "One Kit Contains - 25 Assorted Basic Diodes of 4 different types each. Types: NPN Transistor - 2N3904, BC547 PNP Transistor - 2N3906, BC557 Silicon Diode - 1N4148, Power Diode - 1N4004/4001. Equivalent or better. Wattage: 1W, Current rating: 1A Assorted kit packaged together and labelled.",
    "qty60": "3 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Fundamental passive electronics, current limiting, filtering, switching circuits",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 49,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Button Switch Set",
    "spec": "One Kit Contains - 100 buttons of different types. Types: Push, toggle, rotary, selector and slide switch. Assorted kit packaged together and labelled.",
    "qty60": "3 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 50,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Capacitative touch Module",
    "spec": "MPR 121 with I2C. Voltage Range: 2.5V to 3.6V DC.",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 51,
    "package": "Package 1",
    "category": "Electronics Development",
    "name": "Capacitative Touch Switch Module",
    "spec": "Digital Capacitive touch switch module -TTP223B Voltage Range: 2V to 5V DC.",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 52,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "IR Sensors, Obstacle avoider sensor module",
    "spec": "LM393 Detection distance: 2 - 30 cm Detection angle: 30 - 40°",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 53,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Triple Axis Magnetometer",
    "spec": "3-Axis Magneto resistive Sensors I2C Digital Interface Integrated 12-bit ADC Range of -8 to +8 Gauss 160 Hz Maximum o/p rate Quantity",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 54,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Humidity Sensor",
    "spec": "Operating range: 20 – 95 % RH Temperature: 0 - 60 Celsius Power supply: 1.5V AC (Max sine) Operating frequency: 500Hz - 2kHz",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 55,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "MQ Series",
    "spec": "MQ - 2 Smoke Detection MQ-3 Alcohol - Ethanol Sensor 3 MQ-4 Methane Natural Gas Sensor 3 MQ-5 Methane Liquified Gas Sensor 3 MQ-6 Liquified Petroleum Gas Sensor 3 MQ-7 High Sensitivity CO Carbon Monoxide Sensor Detector 3 MQ-8 Hydrogen Gas Sensor 3 MQ-135 Air Quality Sensor 3",
    "qty60": "3 Units",
    "qty90": "4 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 56,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "IR transmitter/",
    "spec": "TSOP 1738 receiver Switching rate: 38 KHz Voltage Rating: 5V",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 57,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Ultrasonic Sensor Module HC-SR-04 or compatible",
    "spec": "Working Voltage - DC 5V Working current - 15 mA Working Frequency - 40 Hz Range - 1 cm to 4 m Effectual Angle - <15° Measuring Angle - 30° Resolution - 0.3 cm",
    "qty60": "40 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 58,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Triple Axis accelerometer-",
    "spec": "3-axis sensing Small, low profile package 4 mm × 4 mm × 1.45 mm LFCSP Low Power: 350 μA (typical) Single-supply operation: 1.8 V to 3.6 V Temperature stability Quantity",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 59,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "PIR Motion Detector Module",
    "spec": "High digital pulse when motion detected Low digital pulse when idle /no motion detected Sensitivity range (up to 6 m) Power supply: 5V – 12V",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 60,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Pulse Rate Heart Sensor",
    "spec": "Pulse Rate Sensor Finger Based (finger or earlobe) Working voltage 3-5V",
    "qty60": "4 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 61,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Relay Module",
    "spec": "5V 10A - 2 Channel Relay Module. Compatible with Arduino.",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 62,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Relay Module",
    "spec": "5V 10A - 1 Channel Relay Module. Compatible with Arduino.",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 63,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Big Sound microphone module",
    "spec": "Large Electret capsule sound module",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 64,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Big Sound microphone module",
    "spec": "Large Electret capsule sound module",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 65,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Soil Moisture Sensor module",
    "spec": "FC-28 with LM293 comparator Operating Voltage: 3.3V to 5V.",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 66,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Touch Sensor",
    "spec": "Capacitive Touch Sensor Module. TTP22X series. Voltage Range: 2.4V to 5.5V",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 67,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Metal Touch Sensor Module",
    "spec": "KY-036 or equivalent metal touch sensor module",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 68,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Rain Drop Sensor",
    "spec": "Rain Sensitive, Rain Drop Detection Sensor Module. Voltage Range: 3.3V to 5.5V. Size: 5mm X 40mm or equivalent.",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 69,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Flex Sensor",
    "spec": "Flex Sensor. Size - 2.2 Inches",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 70,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Temperature Sensor",
    "spec": "LM35 Full range temperature sensor. Voltage Range: 4V to 30V. Error: ±0.5°C",
    "qty60": "6 Units",
    "qty90": "8 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 71,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Temperature and humidity sensor module",
    "spec": "DHT 11 Voltage Range: 3V to 5V Quantity",
    "qty60": "40 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 72,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Force Pressure Sensor",
    "spec": "Force sensitive resistor with a square, 1.75x1.5\" sensing area",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 73,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Colour Recognition Sensor",
    "spec": "TCS3200 Colour Recognition Sensor",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 74,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Water Flow Sensor",
    "spec": "Arduino Compatible Water flow sensor. 5V DC Input.",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 75,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Sound Sensor",
    "spec": "Sound Sensor Module, Microphones module",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 76,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "IR Sensors Array module for Line Following",
    "spec": "8 IR Sensors Array module for Line Following Operating Voltage: 5V",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 77,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "Power Bank",
    "spec": "10000 mAh 5-volt Power Bank",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 78,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "RFID Reader – Tags",
    "spec": "Current :13-26mA / DC 3.3V Idle Current :10-13mA Sleep Current<80uA Peak Current<30mA Operating Frequency: 13.56MHz<30mA Read range between 20 cm to 1 m",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 79,
    "package": "Package 1",
    "category": "Internet of Things & Sensors",
    "name": "RF Modules Tx & Rx 315 MHz ASK",
    "spec": "Frequency Range: 433.92/315 MHz Supply Voltage: 3 – 6 V Output: 4 – 16 Dbm Low power consumption Easy application",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Wireless IoT communications, cloud telemetry, geo-tracking, smart automation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 80,
    "package": "Package 1",
    "category": "Robotics",
    "name": "Stepper motor with Driver board",
    "spec": "28BYJ-48 ULN2003 5V Stepper Motor + ULN2003 Driver Board",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 81,
    "package": "Package 1",
    "category": "Robotics",
    "name": "DC motor",
    "spec": "12V DC Gear 150 RPM Quantity",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 82,
    "package": "Package 1",
    "category": "Robotics",
    "name": "Servo motors",
    "spec": "Position Servo Angle based Metal Gear Small Servo Metal Gear 10 Continuous Metal Gear Servo 360 10 Small Servo Plastic Gear 40",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 83,
    "package": "Package 1",
    "category": "Robotics",
    "name": "150 RPM BO Motor",
    "spec": "150 RPM BO Motor",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 84,
    "package": "Package 1",
    "category": "Robotics",
    "name": "L298P Motor Driver",
    "spec": "L298P Motor Driver Shield or relative Driver Shield",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 85,
    "package": "Package 1",
    "category": "Robotics",
    "name": "Servo Motor Tester",
    "spec": "CCPM 3 channel Servo Tester",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Consumable",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 86,
    "package": "Package 1",
    "category": "DIY Kit",
    "name": "Robotics DIY Kit",
    "spec": "Robotics DIY kit with programmable intelligent brain/brick.",
    "qty60": "3 Units",
    "qty90": "4 Units",
    "type": "Equipment",
    "application": "Hands-on mechanical assemblies, linkage mechanisms, STEM challenge projects",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 87,
    "package": "Package 1",
    "category": "DIY Kit",
    "name": "Mechanical (Modular) Construction kit",
    "spec": "Metal/plastic mechanical construction kit compatible with electronic equipment.",
    "qty60": "5 Units",
    "qty90": "6 Units",
    "type": "Equipment",
    "application": "Hands-on mechanical assemblies, linkage mechanisms, STEM challenge projects",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 88,
    "package": "Package 1",
    "category": "STEM Learning/App lication Kit",
    "name": "Drone Kit",
    "spec": "Educational Purpose Aerospace Kit 1 Automobile Kit 1 Bio-Medical Kit 1 Agri-Tech Kit 1 Water/ Sanitation Kit 1 Bio Tech Kit 1 Other Potential STEM Application Kit 1 Quantity",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Aeromodelling, flight dynamics, quadcopter stabilization, aerial robotics",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 89,
    "package": "Package 2",
    "category": "Rapid Prototyping Tools",
    "name": "3D Printer Kit and tools",
    "spec": "Printer Type: FDM (Fused Deposition Modelling), Minimum Dimensions: 160mm *160mm *160mm Build Size or 4 litre Build Volume., Nozzle: 0.3mm to 0.4mm nozzle diameter, slicing software should be free or Open source, LCD Screen UI that display print metrics, Good Heated Print bed. Material Compatibility - PLA, ABS, and derivatives of PLA, Ninjaflex Quality Anti-bacterial/fungal Cover. Repair Kit - with spare springs, screws, keys, tweezers, etc.",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Digital additive manufacturing, CAD prototyping, custom robotic chassis printing",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 90,
    "package": "Package 2",
    "category": "Rapid Prototyping Tools",
    "name": "Dedicated UPS/Power back up",
    "spec": "Dedicated UPS/Power Back up with 2-hour battery backup.",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 91,
    "package": "Package 2",
    "category": "Rapid Prototyping Tools",
    "name": "Filament for 3D printer",
    "spec": "Compatible 1000 Grams Filament in 5 different colours",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Digital additive manufacturing, CAD prototyping, custom robotic chassis printing",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 92,
    "package": "Package 2",
    "category": "Rapid Prototyping Tools",
    "name": "Filament Storage Box",
    "spec": "Compatible Filament storage box",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Digital additive manufacturing, CAD prototyping, custom robotic chassis printing",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 93,
    "package": "Package 2",
    "category": "Rapid Prototyping Tools",
    "name": "Set of Arts & Crafts Accessories – e.g.- stationary items and basic prototyping material",
    "spec": "Cardboard Foam core boards 5 20m spool of thick strings various colour 5 Rubber band 100 Popsicle sticks 100 Wood glue – 500 ml 2",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 94,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Hacksaw Frame",
    "spec": "Size: 12 inches",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 95,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Hacksaw blades",
    "spec": "Size: 12 inches",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 96,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Mini Hacksaw Frame",
    "spec": "Size: 6 inches",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 97,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Mini Hacksaw blades",
    "spec": "Size: 6 inches",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 98,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Pliers: 4.5-inch size",
    "spec": "External Straight Nose Circlip Plier 1 Long Nose Plier 1 Combination Mini Plier 1 Wire stripping pliers 1 Bent nose plier 1 Needle nose pliers 1",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 99,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Tweezer Set",
    "spec": "6 Pc Non-Magnetic Tweezer Set Size - 6 inches",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 100,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Ball Pein Hammer",
    "spec": "Ball Pein Hammer Weight - 0.75kg",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 101,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Steel Shaft Claw Hammer",
    "spec": "Claw Hammer Steel Shaft Weight - 0.75kg",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 102,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "C-Clamp",
    "spec": "Metal Clamp: 3-inch size",
    "qty60": "4 Units",
    "qty90": "4 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 103,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Allen Key Set",
    "spec": "10 Piece Ring Imperial Allen Hex key",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 104,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Drill Machine Set",
    "spec": "Drill Machine with accessories Hammer/Screw and clockwise/anticlockwise modes. Power: 500W Chuck capacity - 1 to 10 mm Drill Bits - Masonry, Metal, Wood",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Precision hole boring in plastic, wood, acrylic, and light metal workpieces",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 105,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Drilling Workstation",
    "spec": "Drill Press, Drill Holder and Rotary Tool, Compatible with Drilling machine provided",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Precision hole boring in plastic, wood, acrylic, and light metal workpieces",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 106,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Spanner Set",
    "spec": "12-piece combination Spanner Set Range - 4 mm to 30 mm",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 107,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Vice Normal",
    "spec": "Table top vice",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 108,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Precision Screw Driver Set",
    "spec": "6 Piece Precision Screw Driver Set Types: PH0, PH1, Flat head - 1.4mm, 2mm, 2.4mm, 3mm",
    "qty60": "2 Units",
    "qty90": "3 Units",
    "type": "Equipment",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 109,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Wrench",
    "spec": "Adjustable Universal Wrench",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 110,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Wire Strippers",
    "spec": "Wire Stripper Cutter Plier With Spring -26x6x20 cm (LxWxH)",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 111,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Screwdriver",
    "spec": "40 pc Multi-purpose screwdriver set",
    "qty60": "3 Units",
    "qty90": "3 Units",
    "type": "Equipment",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 112,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Cordless Rotary Multitool Set",
    "spec": "Cordless Rotary multitool with all cutting, grinding, polishing, engraving and drill bits. Speed: Adjustable up to 30000 RPM Battery Type: Li-ion Voltage/current range : 8- 10V, 0-2 A",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 113,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Air Blower",
    "spec": "500 W or more. Variable speed blower",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 114,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Drill Bit Set",
    "spec": "High Quality 13 Pcs HSS Drill Bits Set for Wood, Iron, Aluminium, Plastic etc.",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Precision hole boring in plastic, wood, acrylic, and light metal workpieces",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 115,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "File set",
    "spec": "6 pc file set Working length - 6 inch",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 116,
    "package": "Package 3",
    "category": "Mini File set",
    "name": "6 pc mini file set Working length - 3 inch",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Structural shaping, cutting, mechanical assembly, material fabrication",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 117,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Flexible Cutting Mat",
    "spec": "A3 Size with Marked Pattern and Grids (18\" X 12\")",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 118,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Plastic Storage Drawer/Organiser",
    "spec": "Number of Drawers: 60 or equivalent Drawer size (l*w*d) (inch) : 2*2*5",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 119,
    "package": "Package 3",
    "category": "Mechanical Tools",
    "name": "Pegboard",
    "spec": "Peg board System to mount tools on wall with attachments. Size: 3ft*2ft",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 120,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Hot glue gun",
    "spec": "Works with standard 0.5- inch glue sticks. Temperature - 230 to 280 degree Celsius.",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Equipment",
    "application": "Rapid mechanical adhesion, structural mockups, model prototyping",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 121,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Digital Oscilloscope",
    "spec": "Minimum Bandwidth: 50 Mhz. Minimum number of channels: 2 channels. Sample Rate: 1Gsa/s With inbuilt waveform function generator.",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Scientific measurement, waveform analysis, precision dimensional verification",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 122,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Soldering Kit",
    "spec": "Variable Wattage of Soldering Iron: 15-30 watts/230 volts Soldering Iron Temperature Range: 280°C to 450°C De-Soldering Pump, Soldering Flux (Paste) 100 grams, DE-soldering Copper Braid (Solder Wick) - 1.5m*2mm Compatible Soldering Tip - Bevel, Chisel, Conical - 5 each per kit. Soldering Wire: 20/22 AWG soldering Wire with rosin core flux (100 Grams)",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Equipment",
    "application": "Permanent wire jointing, PCB component assembly, heat shrink insulation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 123,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Adapters",
    "spec": "DC power Adapter with 5V, 2A",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 124,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Adapters",
    "spec": "DC power Adapter with 12V, 2A",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 125,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Electric Screw Driver Set",
    "spec": "Multipurpose Electric screwdriver set. Accessories - Compatible bits Mode - Wireless Battery - Li-ion 3.6V or equivalent with charging dock",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Robotics actuation, robotic arm articulation, rover mobility, precise angle control",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 126,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Dual Temperature Heat Gun",
    "spec": "1800 W Dual Temperature Heat Gun",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Permanent wire jointing, PCB component assembly, heat shrink insulation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 127,
    "package": "Package 3",
    "category": "Electric Tools",
    "name": "Soldering Helping hand",
    "spec": "Specifications: Adjustable crocodile holding clamps/clip. Soldering iron holder. LED light. Magnifying lens.",
    "qty60": "4 Units",
    "qty90": "6 Units",
    "type": "Equipment",
    "application": "Permanent wire jointing, PCB component assembly, heat shrink insulation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 128,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Return measuring tape",
    "spec": "Return measuring tape 5Mx19mm",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Scientific measurement, waveform analysis, precision dimensional verification",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 129,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Stainless Steel Rule",
    "spec": "Stainless Steel 12” / 150 mm Rule",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Equipment",
    "application": "Scientific measurement, waveform analysis, precision dimensional verification",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 130,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Digital Vernier Calliper",
    "spec": "150 mm / 6” Digital Vernier Calliper",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Equipment",
    "application": "Scientific measurement, waveform analysis, precision dimensional verification",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 131,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Spirit Level",
    "spec": "12” Spirit Level",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Environmental perception, distance measurement, automated trigger systems",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 132,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Digital Pen electric Tester",
    "spec": "Voltage tester",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 133,
    "package": "Package 3",
    "category": "Measurement Tools",
    "name": "Digital Multi Meter",
    "spec": "Digital Multi Meter Voltage Current Resistance-7 functions + 19 ranges to cover DC voltage 200mV to 1kV, AC voltage 200 V - 750 V, DC current 200 µA - 10 A Resistance 200 -2 M Ohm and Transistor & diode test.",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Equipment",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 134,
    "package": "Package 3",
    "category": "Biology Kit",
    "name": "DIY Paper Microscope",
    "spec": "DIY Paper microscope. Magnification range - 100x to 2000x",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Cellular observation, bio-STEM investigations, microstructure analysis",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 135,
    "package": "Package 3",
    "category": "Astronomy Equipment",
    "name": "Telescope",
    "spec": "All glass optical components Altazimuth mount suitable for terrestrial and astronomical use minimum 700 mm focal length",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Astronomy, celestial observation, optical physics practicals",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 136,
    "package": "Package 3",
    "category": "Textile Equipment",
    "name": "Sewing Kit",
    "spec": "Semi-Automatic Sewing machine Straight stitch Consumables - 2 set of assorted needles and 10- colour spool set. Quantity",
    "qty60": "1 Units",
    "qty90": "1 Units",
    "type": "Equipment",
    "application": "Wearable electronics, e-textiles, conductive thread wearable innovation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 137,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Glue Sticks",
    "spec": "11 mm x 200mm Hot Melt Glue Stick",
    "qty60": "100 Units",
    "qty90": "150 Units",
    "type": "Consumable",
    "application": "Rapid mechanical adhesion, structural mockups, model prototyping",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 138,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Nuts and Bolts and screw",
    "spec": "Specs - M4X12MM M4X20MM M5X16MM M5X25MM M6X20MM",
    "qty60": "40 Units",
    "qty90": "40 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 139,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Cable Tie",
    "spec": "Small Cable Tie Pack - Pack of 100",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 140,
    "package": "Package 4",
    "category": "General",
    "name": "Medium Cable Tie Pack - Pack of 100",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 141,
    "package": "Package 4",
    "category": "General",
    "name": "Big Cable Tie Pack - Pack of 100",
    "spec": "Mandated technical specifications as per official NITI Aayog ATL inventory.",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 142,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Sand Paper",
    "spec": "Grit Values - 80, 100, 120, 200, 300. 5 Nos of each",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 143,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Power Strip Adaptors",
    "spec": "Standard Quality Extension with 5Amp safety fuse. 5 or more sockets in each extension. 5-meter length of each extension.",
    "qty60": "5 Units",
    "qty90": "5 Units",
    "type": "Consumable",
    "application": "Laboratory power supply distribution, cable management, hardware fastening",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 144,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Bulb Holders",
    "spec": "Regular Hanging Bulb holder",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 145,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "Electric Wires",
    "spec": "Twisted Red black pair",
    "qty60": "20 meters",
    "qty90": "20 meters",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 146,
    "package": "Package 4",
    "category": "Power Supply & accessories",
    "name": "USB TO DC jack cable",
    "spec": "USB to DC jack cable for Battery bank",
    "qty60": "10 Units",
    "qty90": "10 Units",
    "type": "Consumable",
    "application": "Hands-on experiential learning, prototyping, and tinkering experimentation",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 147,
    "package": "Package 4",
    "category": "Safety equipment",
    "name": "First-Aid Kit",
    "spec": "Standard Medical First Aid kit in portable container.",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Consumable",
    "application": "Occupational laboratory safety, personal protection, emergency preparedness",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 148,
    "package": "Package 4",
    "category": "Safety equipment",
    "name": "Fire extinguisher (handy units)",
    "spec": "Powder Type Fire Extinguisher 2KG",
    "qty60": "2 Units",
    "qty90": "2 Units",
    "type": "Consumable",
    "application": "Occupational laboratory safety, personal protection, emergency preparedness",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 149,
    "package": "Package 4",
    "category": "Safety equipment",
    "name": "Safety goggles (with/ without LED torch)",
    "spec": "Polycarbonate Safety goggles Clear lens with no tint",
    "qty60": "30 Units",
    "qty90": "50 Units",
    "type": "Consumable",
    "application": "Occupational laboratory safety, personal protection, emergency preparedness",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 150,
    "package": "Package 4",
    "category": "Safety equipment",
    "name": "Safety Gloves Pairs",
    "spec": "Latex Coating Gloves (Medium Size)",
    "qty60": "10 Units",
    "qty90": "15 Units",
    "type": "Consumable",
    "application": "Occupational laboratory safety, personal protection, emergency preparedness",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  },
  {
    "srNo": 151,
    "package": "Package 4",
    "category": "Safety equipment",
    "name": "Safety Mask",
    "spec": "Filtering efficiency ranging 80 percent when tested against 0.3-micron sodium chloride particle",
    "qty60": "20 Units",
    "qty90": "30 Units",
    "type": "Consumable",
    "application": "Occupational laboratory safety, personal protection, emergency preparedness",
    "refUrl": "https://aim.gov.in/pdf/ATL_Equipment_List/ATL_Equipment_List_60_students.pdf"
  }
];

export const ATL_SUBPAGES: Record<string, AtlSubpageMeta> = {
  overview: {
    slug: 'overview',
    title: 'Atal Tinkering Lab (ATL 2.0) Master Setup Guide & Operational Framework (2026)',
    shortTitle: 'ATL 2.0 Master Hub',
    eyebrow: 'NITI Aayog Flagship Innovation Model',
    badge: 'NITI Aayog Certified',
    readTime: '9 min read',
    heroImage: '/images/categories/technology.jpg',
    heroImageAlt: 'Students prototyping with 3D printer and robotics in modern Atal Tinkering Lab',
    tagline: 'Under the vision of cultivating one million neoteric child innovators across India, NITI Aayog establishes Atal Tinkering Laboratories (ATLs) in schools. Explore the complete 2026 setup blueprint, package guidelines, and operational framework.'
  },
  equipment: {
    slug: 'equipment',
    title: 'ATL Equipment List (Package 1 to 4): Official 60 vs 90 Students Specification (2026)',
    shortTitle: 'Equipment & Packages (60 vs 90)',
    eyebrow: 'Official NITI Aayog Inventory',
    badge: '151 Mandated SKUs',
    readTime: '12 min read',
    heroImage: '/images/categories/engineering.jpg',
    heroImageAlt: 'Comprehensive table of Package 1 to 4 ATL equipment with 3D printers, microcontrollers and tools',
    tagline: 'Itemized, clause-by-clause bill of materials for Package 1 (Electronics & IoT), Package 2 (3D Printing), Package 3 (Mechanical Tools), and Package 4 (Power & Safety) comparing official 60-student and 90-student batch allocations.'
  },
  infrastructure: {
    slug: 'infrastructure',
    title: 'ATL Space, Floor Plan & Room Infrastructure Norms: 1,500 Sq. Ft. Blueprint (2026)',
    shortTitle: 'Space & 1,500 Sq Ft Layout',
    eyebrow: 'Mandatory Architectural Guidelines',
    badge: '1,500 Sq Ft Norm',
    readTime: '8 min read',
    heroImage: '/images/categories/chemistry.jpg',
    heroImageAlt: 'Architectural layout of Atal Tinkering Lab showing 4 functional student zones and furniture',
    tagline: 'Mandatory physical room specifications, 4 functional zones (Ideation, Tinkering, Fabrication, Prototyping), electrical load distribution, ESD rubber matting, and furniture ergonomics required for NITI Aayog compliance.'
  },
  cost: {
    slug: 'cost',
    title: 'ATL Setup Cost & Budget Breakdown: ₹20 Lakh Grant Tranches & PFMS Guide (2026)',
    shortTitle: 'Cost, Budget & ₹20L Grant',
    eyebrow: 'Financial Norms & Audit Protocol',
    badge: '₹20 Lakh Funding',
    readTime: '8 min read',
    heroImage: '/images/categories/mathematics.jpg',
    heroImageAlt: 'Financial budget breakdown chart showing Tranche 1, Tranche 2, and Tranche 3 ATL grant allocation',
    tagline: 'Transparent financial analysis of the ₹20 Lakh Grant-in-Aid: ₹10 Lakh Capital Establishment grant, ₹10 Lakh 5-year O&M envelope, Tranche-1 (₹12 Lakh) upfront credit, Form GFR 12-A submission, and PFMS accounting.'
  },
  vendor: {
    slug: 'vendor',
    title: 'Empanelled Turnkey Vendors for ATL: GeM Procurement, Warranty & Setup Guide (2026)',
    shortTitle: 'GeM Turnkey Vendor Guide',
    eyebrow: 'Government Procurement Protocol',
    badge: 'GeM Registered',
    readTime: '7 min read',
    heroImage: '/images/categories/technology.jpg',
    heroImageAlt: 'Turnkey vendor technicians commissioning 3D printer and testing electronics in school ATL',
    tagline: 'How to select a verified turnkey partner on the Government e-Marketplace (GeM), ensure OEM product warranties, obtain certified teacher master training, and avoid common audit objections during NITI Aayog inspections.'
  }
};
