import { EditorContentType, EditorFeatureConfig } from '../types';

export const CONTENT_TYPE_CONFIGS: Record<EditorContentType, EditorFeatureConfig> = {
  experiment: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: true,
    projectBlocks: false,
    questions: true,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Write scientific experiment objective, procedure, formulas, and observations (Type / for commands)...',
  },
  project: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: true,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Document engineering project problem statement, methodology, circuit schematics, and results (Type / for commands)...',
  },
  blog: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: false,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Write engaging science & technology article (Type / for headings, callouts, images)...',
  },
  article: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: false,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Write detailed educational article or documentation...',
  },
  job: {
    formulas: false,
    graphs: false,
    code: false,
    diagrams: false,
    tables: true,
    images: true,
    videos: false,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: false,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Describe job overview, key responsibilities, qualifications, and candidate benefits (Type / for lists and callouts)...',
  },
  post: {
    formulas: true,
    graphs: false,
    code: true,
    diagrams: false,
    tables: false,
    images: true,
    videos: false,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: false,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Share an update, question, or breakthrough with the CSEEL STEM community...',
  },
  notice: {
    formulas: false,
    graphs: false,
    code: false,
    diagrams: false,
    tables: true,
    images: true,
    videos: false,
    callouts: true,
    experimentBlocks: false,
    projectBlocks: false,
    questions: false,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Write official institutional notice or circular...',
  },
  document: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: true,
    projectBlocks: true,
    questions: true,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Start writing your document (Type / for commands)...',
  },
  course: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: true,
    projectBlocks: true,
    questions: true,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Build curriculum syllabus, lesson modules, and interactive tasks...',
  },
  tutorial: {
    formulas: true,
    graphs: true,
    code: true,
    diagrams: true,
    tables: true,
    images: true,
    videos: true,
    callouts: true,
    experimentBlocks: true,
    projectBlocks: true,
    questions: true,
    aiAssistance: true,
    slashCommands: true,
    characterCount: true,
    placeholder: 'Step-by-step hands-on tutorial with code, diagrams, and tips...',
  },
};
