import { MaterialCategory, MaterialProduct } from '../types/materialTypes';

export const MATERIAL_CATEGORIES: MaterialCategory[] = [
  { key: 'GLS', label: 'Glassware & Flasks', description: 'Borosilicate 3.3 beakers, volumetric flasks, test tubes', badgeColor: 'bg-cyan-50 text-cyan-800 border-cyan-200' },
  { key: 'KIT', label: 'STEM & Robotics Kits', description: 'Arduino, IoT sensors, ATL innovation kits, motors', badgeColor: 'bg-purple-50 text-purple-800 border-purple-200' },
  { key: 'CHM', label: 'Chemical Reagents', description: 'Analytical grade salts, acids, indicators & solutions', badgeColor: 'bg-amber-50 text-amber-800 border-amber-200' },
  { key: 'INS', label: 'Lab Instruments', description: 'Digital multimeters, spectrophotometers, microscopes', badgeColor: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  { key: 'SNS', label: 'Sensors & Modules', description: 'Ultrasonic, temperature, gas, gyro, biometric sensors', badgeColor: 'bg-blue-50 text-blue-800 border-blue-200' },
  { key: 'OPT', label: 'Optics & Lasers', description: 'Prisms, convex/concave lenses, optical benches, lasers', badgeColor: 'bg-rose-50 text-rose-800 border-rose-200' },
  { key: 'BIO', label: 'Biology & Specimens', description: 'Prepared slides, anatomical models, staining sets', badgeColor: 'bg-lime-50 text-lime-800 border-lime-200' },
  { key: 'ELC', label: 'Electronics & Breadboards', description: 'Soldering stations, breadboards, jumper wires, ICs', badgeColor: 'bg-indigo-50 text-indigo-800 border-indigo-200' },
];

export const INITIAL_MATERIAL_PRODUCTS: MaterialProduct[] = [
  {
    id: 'm1',
    slug: 'borosilicate-glass-beaker-set',
    sku: 'CSE-GLS-001',
    name: 'Borosilicate Glass Beaker (Set of 5: 50ml to 1000ml)',
    scientific_name: 'Graduated Borosilicate 3.3 Low Form Griffin Beaker Set',
    common_names: ['Glass Beaker', 'Lab Beaker', 'Graduated Beaker'],
    category: 'GLS',
    categoryLabel: 'Glassware & Flasks',
    brand: 'CSEEL Scientific',
    price: 485,
    original_price: 650,
    discountPercentage: 25,
    rating: 4.9,
    reviews: 142,
    stock: 85,
    current_stock: 85,
    min_order_qty: 1,
    image_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=800&auto=format&fit=crop',
    ],
    tag: 'Bestseller',
    description: 'High quality Borosilicate 3.3 laboratory glass beakers engineered with uniform wall thickness and excellent thermal shock resistance. Features double-scale white ceramic graduations and an extra large marking spot for easy sample identification.',
    specification: 'Material: Borosilicate Glass 3.3 (ISO 3819 / DIN 12331). Temperature resistance up to 500°C. Autoclavable at 121°C.',
    includes: ['1x 50ml Beaker', '1x 100ml Beaker', '1x 250ml Beaker', '1x 500ml Beaker', '1x 1000ml Beaker'],
    safety: 'Wear protective safety goggles and heat-resistant silicone gloves when handling heated liquids.',
    warning: 'Do not rapidly quench hot glassware in cold water.',
    handling: 'Handle with care; inspect for micro-cracks before thermal heating.',
    storage: 'Store inverted on beaker drying rack in clean, dust-free cabinet.',
    warranty: '1 Year Manufacturer Guarantee Against Thermal Cracking',
    delivery_days: 3,
    featured: true,
    is_active: true,
    customerReviews: [
      {
        id: 'r1',
        userId: 'u-101',
        userName: 'Dr. Anita Sharma',
        userRole: 'Teacher',
        rating: 5,
        title: 'Outstanding quality for school chemistry labs',
        comment: 'The graduations are crisp and survive repeated acid wash cycles without fading.',
        date: '2026-08-10',
        verifiedPurchase: true,
        likesCount: 19,
      },
    ],
  },
  {
    id: 'm2',
    slug: 'complete-arduino-iot-stem-kit',
    sku: 'CSE-KIT-002',
    name: 'Complete Arduino IoT & Robotics Starter Kit (45+ Components)',
    scientific_name: 'Microcontroller Educational Hardware Development Kit',
    common_names: ['Arduino Kit', 'Robotics Starter Kit', 'STEM Kit'],
    category: 'KIT',
    categoryLabel: 'STEM & Robotics Kits',
    brand: 'Projectokart STEM',
    price: 1899,
    original_price: 2499,
    discountPercentage: 24,
    rating: 4.8,
    reviews: 218,
    stock: 60,
    current_stock: 60,
    min_order_qty: 1,
    image_url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop',
    ],
    tag: 'NEP-2020 Recommended',
    description: 'The ultimate beginner to advanced robotics toolkit equipped with ATmega328P microcontroller board, 16x2 LCD display, ultrasonic distance sensor, servo motor, DHT11 temp/humidity sensor, breadboard, and 65 jumper wires.',
    specification: 'Operating Voltage: 5V DC via USB or 9V Barrel Jack. 14 Digital I/O Pins, 6 Analog Inputs.',
    includes: ['1x Uno R3 Board', '1x 830-Point Breadboard', '1x Ultrasonic HC-SR04', '1x SG90 Micro Servo', '1x 1602 I2C LCD', '1x Component Box'],
    safety: 'Always disconnect USB power before rewiring circuits on the breadboard.',
    warranty: '2 Year Hardware Replacement Warranty',
    delivery_days: 2,
    featured: true,
    is_active: true,
  },
  {
    id: 'm3',
    slug: 'digital-multimeter-auto-ranging',
    sku: 'CSE-INS-003',
    name: 'Precision Digital Multimeter (Auto-Ranging with Temp Probe)',
    scientific_name: 'True-RMS 6000 Counts Digital Multimeter with Backlight',
    common_names: ['DMM', 'Digital Multimeter', 'Voltmeter-Ammeter'],
    category: 'INS',
    categoryLabel: 'Lab Instruments',
    brand: 'CSEEL Scientific',
    price: 890,
    original_price: 1200,
    discountPercentage: 26,
    rating: 4.7,
    reviews: 95,
    stock: 42,
    current_stock: 42,
    min_order_qty: 1,
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&auto=format&fit=crop',
    ],
    tag: 'Lab Standard',
    description: 'High-accuracy electronic meter designed for physics and electrical engineering experiments. Measures AC/DC Voltage up to 600V, Current up to 10A, Resistance up to 60MΩ, Capacitance, Frequency, and Temperature with K-Type Thermocouple.',
    specification: 'Accuracy: ±0.5% + 3 digits. Safety: CAT III 600V with ceramic fuse protection.',
    includes: ['1x Multimeter Unit', '2x Gold-Plated Test Probes', '1x K-Type Temperature Probe', '1x 9V Battery'],
    safety: 'Never measure current across voltage sources. Always verify lead positions.',
    warranty: '1 Year Full Replacement Warranty',
    delivery_days: 3,
    featured: true,
    is_active: true,
  },
  {
    id: 'm4',
    slug: 'optical-laser-prism-bench-kit',
    sku: 'CSE-OPT-004',
    name: 'Geometrical Optics & Laser Refraction Experiment Bench Kit',
    scientific_name: 'Optics Ray Box & Equilateral Crown Glass Prism Kit',
    common_names: ['Prism Kit', 'Optics Bench', 'Laser Box'],
    category: 'OPT',
    categoryLabel: 'Optics & Lasers',
    brand: 'CSEEL Scientific',
    price: 1250,
    original_price: 1650,
    discountPercentage: 24,
    rating: 4.9,
    reviews: 64,
    stock: 28,
    current_stock: 28,
    min_order_qty: 1,
    image_url: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop',
    ],
    tag: 'Physics Lab Essential',
    description: 'Complete apparatus to demonstrate Snell’s law, total internal reflection, prism dispersion, and focal lengths of bi-convex and bi-concave optical glass lenses with a 3-beam red diode laser generator.',
    specification: 'Prism: High-purity optical flint glass (n=1.62). Laser: 650nm Class 2 Red Diode (<1mW).',
    includes: ['1x 3-Beam Diode Laser', '1x Equilateral Prism', '1x Semi-Circular Glass Block', '1x Convex Lens', '1x Concave Lens', '1x Protractor Grid Sheet'],
    safety: 'Do not look directly into the laser beam or point at reflective metals toward eyes.',
    warranty: '1 Year Manufacturer Warranty',
    delivery_days: 4,
    featured: false,
    is_active: true,
  },
];
